openapi: 3.0.0
info:
  title: Food Delivery API
  version: 1.0.0
  description: API for calculating delivery prices based on distance and item type
components:
  schemas:
    CalculatePriceRequest:
      type: object
      properties:
        zone:
          type: string
          description: Zone name
        organization_id:
          type: integer
          description: ID of the organization
        total_distance:
          type: number
          description: Total distance in kilometers
        item_type:
          type: string
          description: Type of the item (perishable/non-perishable)

    CalculatePriceResponse:
      type: object
      properties:
        total_price:
          type: number
          description: Total price in cents
paths:
  /api/calculate-price:
    post:
      summary: Calculate the price for food delivery
      tags:
        - Calculate Price
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CalculatePriceRequest"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CalculatePriceResponse"
        "400":
          description: Bad request
        "404":
          description: Not found
        "500":
          description: Internal server error
